language: ruby
sudo: required
cache: bundler
rvm:
  - 2.5.1
env:
  global:
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y curl git make
before_script:
  - make update-init update-modules
script:
  - make _site
install:
  - pip install --user awscli
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_STAGING_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: staging
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "staging" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
