title: Resource site for ISO/TC 211 Geographic information/Geomatics
title_html: Geographic technology standard models & schemas

# google_analytics:
#   id: UA-XXXXX-Y

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211
  links:
    - url: /about
      title: About
    - url: /strategic-policy
      title: Strategic Policy Statement
    - url: /faq
      title: FAQ

always_show_committee_link_on_landing: yes

email: open.source@ribose.com

description: >-
  Resource site for ISO/TC 211 Geographic information/Geomatics

tagline: >-
  Links to resources for accessing and using standard models and schemas

baseurl: ""
url: "https://www.isotc211.org"

theme: jekyll-theme-isotc211

awards:
  - title: 2010 Lawrence D. Eicher Leadership Award
    path: /award/2010/09/16/tc211-wins-iso-excellence-award.html

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

nav:
  items:
    - id: home
      url: /
      title: Home
      description: Standard resource links & latest news
    - id: news
      url: /posts
      title: News & Articles

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/

header_pages:
  - home.adoc
  - about.adoc
  - faq.adoc
  - strategic-policy.adoc
