title: ISO/TC 211
title_html: "ISO/TC&nbsp;211"
brand_sub: "Harmonized Resources Maintenance Agency"

theme: jekyll-theme-isotc211

google_analytics:
  id: UA-138578173-1

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211

collections:
  pages:
    output: true
    permalink: /:path/

email: open.source@ribose.com

description: >-
  Resource site for ISO/TC 211 Geographic information/Geomatics

tagline: >-
  Links to resources for accessing and using standard models and schemas

baseurl: ""
url: "https://www.isotc211.org"

markdown: kramdown

plugins:
  - jekyll/vite
  - jekyll-feed
  - jekyll-data
  - jekyll-asciidoc

nav:
  - title: About
    url: /about/
  - title: News
    url: /news/

footer_links:
  - title: Geodetic Registry
    url: https://geodetic.isotc211.org/
  - title: Normative Statements
    url: https://standards.isotc211.org/
  - title: UML Models
    url: http://iso.sparxcloud.com/index.php
  - title: Schemas
    url: https://schemas.isotc211.org
  - title: Terminology
    url: https://isotc211.geolexica.org/
  - title: Ontologies
    url: https://def.isotc211.org
  - title: Registries
    url: https://registry.isotc211.org/

awards:
  - title: Winner of the 2010 Lawrence D. Eicher Leadership Award
    path: /award/2010/09/16/tc211-wins-iso-excellence-award.html

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211

favicon_svg: /assets/favicon.svg
favicon_ico: /assets/favicon.ico

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - .sass-cache
  - vite.config.ts
  - postcss.config.js
  - bin
  - _frontend
  - config/vite.json
