title: Geomatics

email: open.source@ribose.com

description: >-
  The resource site for ISO/TC 211 Geographic information/Geomatics

tagline: >-
  Resource site for geographic information

baseurl: ""
url: "https://www.isotc211.org"

theme: jekyll-theme-isotc211

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: Committee Site

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About ISO/TC 211
  strategic-policy:
    url: /strategic-policy
    title: Strategic Policy Statement

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/

header_pages:
  - home.adoc
  - about.adoc
  - strategic-policy.adoc
