---
layout: home
permalink: /
---
== General

This page contain links to resources for accessing and using models and schemas from the ISO/TC 211 Standards.

For more information, please visit the https://committee.iso.org/home/tc211[ISO/TC 211 committee page].

== UML Models (HMMG)

HTML views of the Harmonized UML Model are available for:

* link:hmmg/HTML/ConceptualModels/[Conceptual models]; and
* link:hmmg/HTML/ImplementationModels/[Implementation Models].

The https://github.com/ISO-TC211/HMMG[GitHub repository] for the ISO/TC 211 Harmonized Model Maintenance Group (HMMG) contains model files, information about the Harmonized Model, and https://github.com/ISO-TC211/HMMG/wiki[how to work with it].


== XML Schemas (XMG)

ISO/TC 211 XML Schemas are located in two places:

* ISO/TC 211: https://schemas.isotc211.org

* ISO: https://standards.iso.org/iso

Each part of each standard has a directory in this format
`StandardNumber/PartNumber/NamespacePrefix/Version`.

XML Schemas are provided under the "2005/" directory, as referred by ISO/TC 211 standards, including:

* ISO/TS 19157-2
* ISO/TS 19139

NOTE: Example: https://schemas.isotc211.org/19115/-3/cit/1.0 (or http://standards.iso.org/iso/19115/-3/cit/1.0)
; https://schemas.isotc211.org/19157/-2/mdq/1.0 (or http://standards.iso.org/iso/19157/-2/mdq/1.0).


== Ontologies (GOM)

ISO/TC 211 Ontologies are located at https://def.isotc211.org

Ontology representations of the ISO/TC 211 Standards are maintained in the https://github.com/ISO-TC211/GOM[GitHub repository] for the ISO/TC 211 Group on Ontology Management (GOM).
