---
layout: home
permalink: /
---
== General

This page contain links to resources for accessing and using models and schemas from the ISO/TC 211 Standards.

For more information, please visit the https://committee.iso.org/home/tc211[ISO/TC 211 committee page].

== UML Models (HMMG)

HTML views of the Harmonized UML Model are available for:

* link:hmmg/ConceptualModels/index.htm[Conceptual models]; and
* link:hmmg/ImplementationModels/index.htm[Implementation Models].

The https://github.com/ISO-TC211/HMMG[GitHub repository] for the ISO/TC 211 Harmonized Model Maintenance Group (HMMG) contains model files, information about the Harmonized Model, and https://github.com/ISO-TC211/HMMG/wiki[how to work with it].


== XML Schemas (XMG)

The ISO/TC 211 XML Schema repository is located at http://standards.iso.org/iso.

Each part of each standard has a directory like: http://standards.iso.org/iso/StandardNumber/PartNumber/NamespacePrefix/Version.

XML Schemas are provided under the "2005/" directory, as referred by ISO/TC 211 standards, including:

* ISO/TS 19157-2
* ISO/TS 19139

NOTE: Example: http://standards.iso.org/iso/19115/-3/cit/1.0 or http://standards.iso.org/iso/19157/-2/mdq/1.0.

Comments, suggestions, change requests and revisions are managed in the https://github.com/ISO-TC211/XML[GitHub repository] for the ISO/TC 211 XML Maintenance Group (XMG)


== Ontologies (GOM)

Ontology representations of the ISO/TC 211 Standards are maintained in the https://github.com/ISO-TC211/GOM[GitHub repository] for the ISO/TC 211 Group on Ontology Management (GOM).
